import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // This will be caught by the App component and shown to the user.
  throw new Error("API_KEY environment variable not set. Please ensure it's configured.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (base64Data: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64Data,
      mimeType,
    },
  };
};

export const removeMask = async (imageDataUrl: string, age: string): Promise<string> => {
  try {
    const model = 'gemini-2.5-flash-image';
    
    let prompt = "This is a photo of a person wearing a face mask.";
    if (age && age !== 'Unspecified') {
      prompt += ` The person is approximately in the '${age}' age range.`;
    }
    prompt += " Please remove the mask from the person's face. Reconstruct the covered area (nose, mouth, chin) to look natural and photorealistic, seamlessly matching the lighting, skin tone, and texture of the rest of the face.";

    const [header, base64Data] = imageDataUrl.split(",");
    if (!header || !base64Data) {
        throw new Error("Invalid image data URL format");
    }
    const mimeTypeMatch = header.match(/:(.*?);/);
    if (!mimeTypeMatch || !mimeTypeMatch[1]) {
        throw new Error("Could not extract MIME type from data URL");
    }
    const mimeType = mimeTypeMatch[1];
    
    const imagePart = fileToGenerativePart(base64Data, mimeType);
    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
        model,
        contents: {
            parts: [imagePart, textPart]
        },
        config: {
            responseModalities: [Modality.IMAGE]
        }
    });
    
    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }
    throw new Error("No image was generated by the API. The model may have refused the request.");
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to remove mask: ${error.message}`);
    }
    throw new Error("An unknown error occurred while communicating with the AI.");
  }
};

export const editImage = async (imageDataUrl: string, prompt: string): Promise<string> => {
    try {
      const model = 'gemini-2.5-flash-image';
      
      const [header, base64Data] = imageDataUrl.split(",");
      if (!header || !base64Data) {
          throw new Error("Invalid image data URL format");
      }
      const mimeTypeMatch = header.match(/:(.*?);/);
      if (!mimeTypeMatch || !mimeTypeMatch[1]) {
          throw new Error("Could not extract MIME type from data URL");
      }
      const mimeType = mimeTypeMatch[1];
      
      const imagePart = fileToGenerativePart(base64Data, mimeType);
      const textPart = { text: prompt };
  
      const response = await ai.models.generateContent({
          model,
          contents: {
              parts: [imagePart, textPart]
          },
          config: {
              responseModalities: [Modality.IMAGE]
          }
      });
      
      for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
              const base64ImageBytes: string = part.inlineData.data;
              return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
          }
      }
      throw new Error("No image was generated by the API during editing. The model may have refused the request.");
    } catch (error) {
      console.error("Error calling Gemini API for editing:", error);
      if (error instanceof Error) {
          throw new Error(`Failed to edit image: ${error.message}`);
      }
      throw new Error("An unknown error occurred while communicating with the AI for editing.");
    }
  };
  